name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '26'
          elixir-version: '1.16'
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - name: Run tests with coverage
        run: |
          set +e
          mix test --cover
          exit 0
      - name: Generate lcov coverage
        run: mix coveralls.lcov
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cover/lcov.info
          fail_ci_if_error: false